development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || "default" %>
  email_secret: <%= ENV['EMAIL_SECRET'] || "default" %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  email_secret: <%= ENV['EMAIL_SECRET'] %>
